/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as AuthenticatedAyarlarRouteImport } from './routes/_authenticated/ayarlar'
import { Route as AuthenticatedGorevlerimRouteImport } from './routes/_authenticated/gorevlerim'
import { Route as AuthenticatedMusterilerRouteImport } from './routes/_authenticated/musteriler'
import { Route as AuthenticatedOnayliIslerRouteImport } from './routes/_authenticated/onayli-isler'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPeriyodikBakimlarRouteImport } from './routes/_authenticated/periyodik-bakimlar'
import { Route as AuthenticatedServisFormlariRouteImport } from './routes/_authenticated/servis-formlari'
import { Route as AuthenticatedTeknisyenlerRouteImport } from './routes/_authenticated/teknisyenler'
import { Route as AuthenticatedIsIdRouteImport } from './routes/_authenticated/is.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAyarlarRoute = AuthenticatedAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGorevlerimRoute = AuthenticatedGorevlerimRouteImport.update({
  id: '/gorevlerim',
  path: '/gorevlerim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusterilerRoute = AuthenticatedMusterilerRouteImport.update({
  id: '/musteriler',
  path: '/musteriler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnayliIslerRoute =
  AuthenticatedOnayliIslerRouteImport.update({
    id: '/onayli-isler',
    path: '/onayli-isler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeriyodikBakimlarRoute =
  AuthenticatedPeriyodikBakimlarRouteImport.update({
    id: '/periyodik-bakimlar',
    path: '/periyodik-bakimlar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServisFormlariRoute =
  AuthenticatedServisFormlariRouteImport.update({
    id: '/servis-formlari',
    path: '/servis-formlari',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeknisyenlerRoute =
  AuthenticatedTeknisyenlerRouteImport.update({
    id: '/teknisyenler',
    path: '/teknisyenler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIsIdRoute = AuthenticatedIsIdRouteImport.update({
  id: '/is/$id',
  path: '/is/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/gorevlerim': typeof AuthenticatedGorevlerimRoute
  '/musteriler': typeof AuthenticatedMusterilerRoute
  '/onayli-isler': typeof AuthenticatedOnayliIslerRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/periyodik-bakimlar': typeof AuthenticatedPeriyodikBakimlarRoute
  '/servis-formlari': typeof AuthenticatedServisFormlariRoute
  '/teknisyenler': typeof AuthenticatedTeknisyenlerRoute
  '/is/$id': typeof AuthenticatedIsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/gorevlerim': typeof AuthenticatedGorevlerimRoute
  '/musteriler': typeof AuthenticatedMusterilerRoute
  '/onayli-isler': typeof AuthenticatedOnayliIslerRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/periyodik-bakimlar': typeof AuthenticatedPeriyodikBakimlarRoute
  '/servis-formlari': typeof AuthenticatedServisFormlariRoute
  '/teknisyenler': typeof AuthenticatedTeknisyenlerRoute
  '/is/$id': typeof AuthenticatedIsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/giris': typeof GirisRoute
  '/_authenticated/ayarlar': typeof AuthenticatedAyarlarRoute
  '/_authenticated/gorevlerim': typeof AuthenticatedGorevlerimRoute
  '/_authenticated/musteriler': typeof AuthenticatedMusterilerRoute
  '/_authenticated/onayli-isler': typeof AuthenticatedOnayliIslerRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/periyodik-bakimlar': typeof AuthenticatedPeriyodikBakimlarRoute
  '/_authenticated/servis-formlari': typeof AuthenticatedServisFormlariRoute
  '/_authenticated/teknisyenler': typeof AuthenticatedTeknisyenlerRoute
  '/_authenticated/is/$id': typeof AuthenticatedIsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/ayarlar'
    | '/gorevlerim'
    | '/musteriler'
    | '/onayli-isler'
    | '/panel'
    | '/periyodik-bakimlar'
    | '/servis-formlari'
    | '/teknisyenler'
    | '/is/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/giris'
    | '/ayarlar'
    | '/gorevlerim'
    | '/musteriler'
    | '/onayli-isler'
    | '/panel'
    | '/periyodik-bakimlar'
    | '/servis-formlari'
    | '/teknisyenler'
    | '/is/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/giris'
    | '/_authenticated/ayarlar'
    | '/_authenticated/gorevlerim'
    | '/_authenticated/musteriler'
    | '/_authenticated/onayli-isler'
    | '/_authenticated/panel'
    | '/_authenticated/periyodik-bakimlar'
    | '/_authenticated/servis-formlari'
    | '/_authenticated/teknisyenler'
    | '/_authenticated/is/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GirisRoute: typeof GirisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ayarlar': {
      id: '/_authenticated/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AuthenticatedAyarlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gorevlerim': {
      id: '/_authenticated/gorevlerim'
      path: '/gorevlerim'
      fullPath: '/gorevlerim'
      preLoaderRoute: typeof AuthenticatedGorevlerimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/musteriler': {
      id: '/_authenticated/musteriler'
      path: '/musteriler'
      fullPath: '/musteriler'
      preLoaderRoute: typeof AuthenticatedMusterilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onayli-isler': {
      id: '/_authenticated/onayli-isler'
      path: '/onayli-isler'
      fullPath: '/onayli-isler'
      preLoaderRoute: typeof AuthenticatedOnayliIslerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/periyodik-bakimlar': {
      id: '/_authenticated/periyodik-bakimlar'
      path: '/periyodik-bakimlar'
      fullPath: '/periyodik-bakimlar'
      preLoaderRoute: typeof AuthenticatedPeriyodikBakimlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servis-formlari': {
      id: '/_authenticated/servis-formlari'
      path: '/servis-formlari'
      fullPath: '/servis-formlari'
      preLoaderRoute: typeof AuthenticatedServisFormlariRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teknisyenler': {
      id: '/_authenticated/teknisyenler'
      path: '/teknisyenler'
      fullPath: '/teknisyenler'
      preLoaderRoute: typeof AuthenticatedTeknisyenlerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/is/$id': {
      id: '/_authenticated/is/$id'
      path: '/is/$id'
      fullPath: '/is/$id'
      preLoaderRoute: typeof AuthenticatedIsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAyarlarRoute: typeof AuthenticatedAyarlarRoute
  AuthenticatedGorevlerimRoute: typeof AuthenticatedGorevlerimRoute
  AuthenticatedMusterilerRoute: typeof AuthenticatedMusterilerRoute
  AuthenticatedOnayliIslerRoute: typeof AuthenticatedOnayliIslerRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPeriyodikBakimlarRoute: typeof AuthenticatedPeriyodikBakimlarRoute
  AuthenticatedServisFormlariRoute: typeof AuthenticatedServisFormlariRoute
  AuthenticatedTeknisyenlerRoute: typeof AuthenticatedTeknisyenlerRoute
  AuthenticatedIsIdRoute: typeof AuthenticatedIsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAyarlarRoute: AuthenticatedAyarlarRoute,
  AuthenticatedGorevlerimRoute: AuthenticatedGorevlerimRoute,
  AuthenticatedMusterilerRoute: AuthenticatedMusterilerRoute,
  AuthenticatedOnayliIslerRoute: AuthenticatedOnayliIslerRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPeriyodikBakimlarRoute: AuthenticatedPeriyodikBakimlarRoute,
  AuthenticatedServisFormlariRoute: AuthenticatedServisFormlariRoute,
  AuthenticatedTeknisyenlerRoute: AuthenticatedTeknisyenlerRoute,
  AuthenticatedIsIdRoute: AuthenticatedIsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GirisRoute: GirisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
